version: '3'

services:
  app:
    image: hardrack-twitch-overlay
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - TWITCH_OAUTH_URL=${TWITCH_OAUTH_URL}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
